#環工所 林憲瑋 R06541132 電影:牠

library(Rfacebook)
library(ggplot2)
library(scales)
library(readxl)
library(ggpubr)

token <- 'EAACEdEose0cBAOrDiPZBDPcPQ7jz1jr8P9sAHB7ArXBgXPIzL5qKwkvPmbzulSgt9fky74qE0cFfhNOuddFMkl88qPp6DlVONSoEEhM0Kxe4ibsWssttZBSdjIpZCA5c3JZBacpR62FYvYScehfZAGK4EvZBeM2I46JYGu4BmylTQTIUoAlVDRDZALwmtKzXfZBrPcgPmYN8JQZDZD'

# 9/8電影上映前到10/27下檔所有貼文
page <- getPage("1623540471295575", token = token, n=1000, since='2017/09/08', until = '2017/10/27')
## convert Facebook date format to R date format
format.facebook.date <- function(datestring) {
  date <- as.POSIXct(datestring, format = "%Y-%m-%dT%H:%M:%S+0000", tz = "GMT")
}
# aggregate metric counts over month
aggregate.metric <- function(metric) {
  m <- aggregate(page[[paste0(metric, "_count")]], list(month = page$month),
    mean)
  m$month <- as.Date(paste0(m$month, "-15"))
  m$metric <- metric
  return(m)
}
# create data frame with average metric counts per month
page$datetime <- format.facebook.date(page$created_time)
page$month <- format(page$datetime, "%Y-%m")
df.list <- lapply(c("likes", "comments", "shares"), aggregate.metric)
df <- do.call(rbind, df.list)

# visualize evolution in metric
## 貼文平均comments, like, share 
ggplot(df, aes(x = df$month, y = x, group = metric)) +
  geom_line(aes(color = metric)) +
  scale_x_date(date_breaks = "1 month", date_labels = "%Y \n %m")+
  scale_y_log10("Average count per post",
  breaks = c(0, 10, 100, 500, 1000, 2500, 5000, 10000, 15000))+
  geom_point()+
  theme_bw() +
  theme(axis.title.x = element_blank())
